<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image Validate Facebook</name>
   <tag></tag>
   <elementGuidId>1bdf1270-2edf-4a85-8bc4-07505fd010aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_popup_cta_form']/div/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.xz74otr.x14hiurz.x1v8p93f.x1o3jo1z.x16stqrj.xv5lvn5.x1rl75mt.x19t5iym.xz7t8uv.x13xmedi.x13fuv20.x18b5jzi.x1q0q8m5.x1t7ytsu.xmn4e3e.x1if355w.x2x41l1.xct1zlm.x14vqqas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#login_popup_cta_form img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eae52567-b349-46b3-94cc-7f5358656a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d579c7d9-612c-4d71-8b22-87d151245bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f39ae905-7c02-480f-aaa4-fe3dc383d7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xz74otr x14hiurz x1v8p93f x1o3jo1z x16stqrj xv5lvn5 x1rl75mt x19t5iym xz7t8uv x13xmedi x13fuv20 x18b5jzi x1q0q8m5 x1t7ytsu xmn4e3e x1if355w x2x41l1 xct1zlm x14vqqas</value>
      <webElementGuid>9cb1691c-0a5a-491a-b730-6115b8a0d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin-when-cross-origin</value>
      <webElementGuid>e86a9c97-f0ca-48cc-97b6-c14f0d401dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/icons/FBLogo_Blueprint.png</value>
      <webElementGuid>8c7f4f17-aa15-4c6d-ac3b-9a243a87eaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_popup_cta_form&quot;)/div[@class=&quot;x1tfhste x1dqj196 x14ler8 xvc51xn x2b8uid&quot;]/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z x78zum5 xdt5ytf x2lah0s x193iq5w x6s0dn4&quot;]/div[@class=&quot;xwxc41k&quot;]/div[@class=&quot;x1rg5ohu x1n2onr6 x3ajldb x1ja2u2z&quot;]/div[@class=&quot;x1c9tyrk xeusxvb x1pahc9y x1ertn4p x10l6tqk xhtitgo&quot;]/img[@class=&quot;xz74otr x14hiurz x1v8p93f x1o3jo1z x16stqrj xv5lvn5 x1rl75mt x19t5iym xz7t8uv x13xmedi x13fuv20 x18b5jzi x1q0q8m5 x1t7ytsu xmn4e3e x1if355w x2x41l1 xct1zlm x14vqqas&quot;]</value>
      <webElementGuid>020e677c-93ee-4836-b179-434a14af309a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_popup_cta_form']/div/div/div/div/div/div/div/img</value>
      <webElementGuid>436a83cc-e9cd-46c4-a733-95a0a26306ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/img</value>
      <webElementGuid>69c9b191-4522-4b8a-887f-de9f27f50730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/icons/FBLogo_Blueprint.png']</value>
      <webElementGuid>9036d7d4-273a-4b01-a7c4-145d1b206674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
