<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>End2End</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>15e5c855-2c68-47f1-bce3-ba390dd040ee</testSuiteGuid>
   <testCaseLink>
      <guid>440aadef-b5fe-4809-a0dc-aa0e6ec796ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E2E/TC_E2E_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fb22a0e-19ca-4806-a674-cda03e4cda49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>685d318c-c52b-4b58-a83a-cf5dfaf1f827</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d8fbe83-8d23-48de-8a79-4a200ce0214c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/E2E/TC_E2E_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9b319a-189e-47f5-906f-8fbb07a34318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f94acb34-f9f5-4601-b6c7-f7917c2302d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
